import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Sidebar navigation items
  const navItems = [
    { name: "Dashboard", href: "/" },
    { name: "Media Upload", href: "/media-upload" },
    { name: "Data Browser", href: "/data" },
    { name: "Scheduler", href: "/scheduler" },
    { name: "Tasks", href: "/tasks" },
    { name: "Settings", href: "/settings" },
  ];
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen bg-background">
          <aside className="w-64 bg-sidebar border-r p-6 flex flex-col gap-4">
            <div className="font-bold text-xl mb-8">SchedulerX</div>
            <nav className="flex flex-col gap-2">
              {navItems.map((item) => (
                <a
                  key={item.href}
                  href={item.href}
                  className="rounded-md px-3 py-2 hover:bg-accent hover:text-accent-foreground transition-colors"
                >
                  {item.name}
                </a>
              ))}
            </nav>
          </aside>
          <main className="flex-1 p-8 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
